apiVersion: v1
kind: Service
metadata:
  name: ranking-service
  namespace: llm-serving
  labels:
    app: ranking-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ranking-service
